"""Apply traceable organizer-derived signal parameters to a SUMO network."""

from __future__ import annotations

import hashlib
import json
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Any


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _green_weights(count: int, turns: dict[str, float]) -> list[float]:
    through = float(turns.get("straight", 0.5)) + float(turns.get("right", 0.25))
    protected = max(0.05, float(turns.get("left", 0.25)))
    values = [through if index % 2 == 0 else protected for index in range(count)]
    total = sum(values)
    return [value / total for value in values]


def apply_parameter_transfer(
    *,
    net_file: Path,
    parameter_file: Path,
    selection_file: Path,
    output_file: Path,
) -> dict[str, Any]:
    """Write transferred cycle plans into a generated SUMO network.

    Phase states and conflict link indices remain those generated by netconvert;
    only static timing and offsets are changed. This preserves SUMO's validated
    conflict structure while making the organizer-derived timing evidence an
    actual executable input.
    """

    parameters = json.loads(parameter_file.read_text(encoding="utf-8"))
    selection = json.loads(selection_file.read_text(encoding="utf-8"))
    input_network_sha256 = _sha256(net_file)
    tree = ET.parse(net_file)
    root = tree.getroot()
    edge_functions = {
        edge.attrib["id"]: edge.attrib.get("function") for edge in root.findall("edge")
    }
    crossing_indices_by_tl: dict[str, set[int]] = {}
    for connection in root.findall("connection"):
        tl_id = connection.attrib.get("tl")
        link_index = connection.attrib.get("linkIndex")
        if (
            tl_id is not None
            and link_index is not None
            and edge_functions.get(connection.attrib.get("to", "")) == "crossing"
        ):
            crossing_indices_by_tl.setdefault(tl_id, set()).add(int(link_index))
    intersection_parameters = parameters["intersections"]
    applications: dict[str, dict[str, Any]] = {}
    for tl_logic in root.findall("tlLogic"):
        logic_id = tl_logic.attrib["id"]
        item = intersection_parameters.get(logic_id)
        if item is None:
            continue
        phases = tl_logic.findall("phase")
        green_phases = [
            phase
            for phase in phases
            if "G" in phase.attrib["state"] or "g" in phase.attrib["state"]
        ]
        if not green_phases:
            continue
        non_green_duration = sum(
            float(phase.attrib["duration"]) for phase in phases if phase not in green_phases
        )
        requested_cycle = float(item["recommended_cycle_s"])
        crossing_indices = crossing_indices_by_tl.get(logic_id, set())
        minimum_green_durations = [
            (
                10.0
                if any(
                    index < len(phase.attrib["state"])
                    and phase.attrib["state"][index] in {"G", "g"}
                    for index in crossing_indices
                )
                else 5.0
            )
            for phase in green_phases
        ]
        cycle = max(
            requested_cycle,
            non_green_duration + sum(minimum_green_durations),
        )
        distributable_green = cycle - non_green_duration - sum(minimum_green_durations)
        weights = _green_weights(len(green_phases), item["turn_ratios"])
        applied_green: list[float] = []
        for phase, weight, minimum_green in zip(
            green_phases,
            weights,
            minimum_green_durations,
            strict=True,
        ):
            duration = minimum_green + distributable_green * weight
            phase.set("duration", f"{duration:.1f}")
            applied_green.append(round(duration, 1))
        actual_cycle = sum(float(phase.attrib["duration"]) for phase in phases)
        tl_logic.set("offset", "0")
        applications[logic_id] = {
            "parameter_provenance": item["parameter_provenance"],
            "requested_cycle_s": requested_cycle,
            "applied_cycle_s": round(actual_cycle, 1),
            "green_phase_durations_s": applied_green,
            "turn_ratios_used": item["turn_ratios"],
            "balanced_peak_flow_veh_h": item["balanced_peak_flow_veh_h"],
            "pedestrian_crossing_link_count": len(crossing_indices),
            "pedestrian_minimum_green_s": 10.0 if crossing_indices else None,
        }
    corridor = selection.get("core_corridor", [])
    distance_by_pair = {
        frozenset((edge["source"], edge["target"])): float(edge["road_distance_m"])
        for edge in selection.get("topology_edges", [])
    }
    cumulative_distance = 0.0
    previous: str | None = None
    logic_by_id = {logic.attrib["id"]: logic for logic in root.findall("tlLogic")}
    for intersection_id in corridor:
        if previous is not None:
            cumulative_distance += distance_by_pair.get(
                frozenset((previous, intersection_id)),
                0.0,
            )
        logic = logic_by_id.get(intersection_id)
        application = applications.get(intersection_id)
        if logic is not None and application is not None:
            cycle = float(application["applied_cycle_s"])
            offset = round((cumulative_distance / 12.0) % cycle, 1)
            logic.set("offset", f"{offset:.1f}")
            application["corridor_offset_s"] = offset
        previous = intersection_id
    ET.indent(tree, space="    ")
    tree.write(output_file, encoding="utf-8", xml_declaration=True)
    return {
        "schema_version": "1.0",
        "parameter_file": str(parameter_file),
        "parameter_file_sha256": _sha256(parameter_file),
        "input_network_sha256": input_network_sha256,
        "output_network_sha256": _sha256(output_file),
        "applied_intersection_count": len(applications),
        "applications": applications,
        "route_choice_use": (
            "mean organizer-derived left-plus-right turn ratio controls "
            "alternative-route sampling share"
        ),
        "evidence_boundary": parameters.get("evidence_boundary"),
    }


def write_application_manifest(result: dict[str, Any], output_file: Path) -> None:
    """Persist a readable application audit next to the generated scenario."""

    output_file.write_text(
        json.dumps(result, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
